spring:
  application:
    name: weshopify-platform-services-registry

server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: ${REGISTRY_HOST_NAME:localhost}
    prefer-ip-address: true
  
