spring: 
  application: 
    name: weshopify-platform-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # to locate the routes in the registry
      routes:
      
       #Categories service route
       - id: WESHOPIFY-CATEGORY-SERVICE
         uri: lb://WESHOPIFY-CATEGORY-SERVICE
         predicates: 
          - Path=/gateway-catg-sv/**
         filters:
            - RewritePath=/gateway-catg-sv/(?<segment>.*),/${segment}
            
         #Brands Service Route 
       - id: WESHOPIFY-BRANDS-SERVICE
         uri: lb://WESHOPIFY-BRANDS-SERVICE
         predicates: 
          - Path=/gateway-brands-svc/**
         filters:
            -  RewritePath=/gateway-brands-svc/(?<segment>.*),/${segment}
            
       - id: openapi
         uri: http://localhost:${server.port}
         predicates:
          - Path=/v3/api-docs/**
         filters:
          - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_HOST:localhost}:${SERVICE_REGISTRY_PORT:8761}/eureka/
  instance:
    hostname: ${SERVICE_REGISTRY_HOST:localhost}
    prefer-ip-address: true
    
management:
  # from the springboot3.x onwards we have to 
  #explicitely enable gateway endpoint
  endpoint:
    gateway:
      enabled: true
      
  endpoints:
    web:
      exposure:
        include: "*"
        
server:
  port: 5012
  
#springdoc:
#  api-docs:
#    enabled: true
#    path: /api-docs
#  swagger-ui:
#    enabled: true
#  packages-to-scan: com.weshopify.platform
